alpha_use: false
att_num: 0
attn_pdrop: 0.1
batch_size: 512
block_size: 92
data_test: ./datasets/moses2_test2.smi
data_train: ./datasets/chembl_clean_smi_len_token2.smi
embd_pdrop: 0.1
learning_rate: 0.0003
lstm: false
lstm_layers: 0
max_len: 92
n_embd: 256
n_head: 8
n_layer: 8
num_epoch: 30
num_props: 0
resid_pdrop: 0.1
sample: false
save: ./save/chembl/crossdocked/
scaffold_maxlen: 0
seed: 666
vocab_path: ./vocab/crossdocked/crossdocked_merged_vocab.yaml
vocab_size: 48
weight_decay: 0.0005
which_vocab: char
