batch_size: 32
dataset: crossdocked
learning_rate: 0.0005
num_epoch: 30
out_dir: ./save/pre/crossdocked/char/all/2025_10_07_09/
pocket_dir: /home/cyy/workspace/data/crossdocked_pocket10/
seed: 42
smiles_dir: ./data_crossdocked/final_filter_train.yaml
vocab: char
vocab_path: ./data_crossdocked/char_merged_vocab.yaml
weight_decay: 0.0005
