result_dir: ./save/pre/crossdocked/char/all/2025_01_12_16/
pocket_dir: ./case_study/7D5U/7d5u_remove_mol.pdb
save_dir: ./case_study/7D5U/
pocket_name: 7d5u
molecule_nums: 300                        
block_size: 119                           
top_k: 30                                
temperature: 1
sample_num: 1   
sample_type: True                        
test_dir: ./data_crossdocked/test.yaml
case_study: True  
